### ISSUE TITLE
Appcache will prevent _ANY_ future updates to site

### ISSUE THREAD

**Issue by diddledan** [alcor/itty-bitty#13]
ref: https://alistapart.com/article/application-cache-is-a-douchebag

Notably, the current manifest lists that everything starting from `/` should be cached. That means that the appcache manifest is included in the cached file set. Appcache will only update the cached files when the manifest is changed, but as the manifest is included in the cached file set then Appcache will never know that the manifest has changed because it will serve the cached manifest first, and never check for an update.

**Comment by alcor** [comment]
(first, totally agreed. This was a hack to see if I could get basic offline viewing working). 

It has been working so far. it appears only to cache the root html, and not any other content.

Having to poke the manifest each time there is an update is a bit lame :)

**Comment by diddledan** [comment]
It promises out of the box offline capabilities, but there's so many quirks that it is just as painful as trying to figure out how to use the serviceworker api. I don't really like either method because you either have quirks, or need to have a build phase of deployment to create a service worker using something like workbox, or need to figure out how to write a suitable service worker from scratch rather than using workbox.

**Comment by alcor** [comment]
I removed the / as the manifest caches the document that references it. It still appears to be working as well as can be hoped (and is allowing these sites to work ~offline with minimal fuss), so closing.
