### ISSUE TITLE
Content Security Policy errors - Editor not working in Chrome

### ISSUE THREAD

**Issue by mayel** [alcor/itty-bitty#20]
Running Chrome (Version 68.0.3440.42 (Official Build) beta (64-bit) 
with many extensions (can provide list if needed)
and getting the following errors:

Refused to load the script 'https://itty.bitty.site/lzma/lzma_worker-min.js' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

edit:1 Refused to load the script 'https://itty.bitty.site/jquery-3.3.1.min.js' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

edit:1 Refused to load the script 'https://itty.bitty.site/data.js' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

edit:1 Refused to load the script 'https://itty.bitty.site/edit.js' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

edit:11 Refused to load the stylesheet 'https://itty.bitty.site/edit.css' because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' 'self'".

chext_driver.js:48 Uncaught DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.
    at el.Fl [as nh] (file:///Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/mclkkofklkfljcocdinagocijmpgbhab/5.8.0.2_0/chext_driver.js:48:208)
    at Sr (file:///Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/mclkkofklkfljcocdinagocijmpgbhab/5.8.0.2_0/chext_driver.js:126:413)
    at new jx (file:///Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/mclkkofklkfljcocdinagocijmpgbhab/5.8.0.2_0/chext_driver.js:201:197)
    at new nx (file:///Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/mclkkofklkfljcocdinagocijmpgbhab/5.8.0.2_0/chext_driver.js:202:67)
    at new px (file:///Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/mclkkofklkfljcocdinagocijmpgbhab/5.8.0.2_0/chext_driver.js:202:224)
    at file:///Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/mclkkofklkfljcocdinagocijmpgbhab/5.8.0.2_0/chext_driver.js:222:322
    at file:///Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/mclkkofklkfljcocdinagocijmpgbhab/5.8.0.2_0/chext_driver.js:222:60
    at Array.reduce (<anonymous>)
    at ky (file:///Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/mclkkofklkfljcocdinagocijmpgbhab/5.8.0.2_0/chext_driver.js:238:391)
    at new ly (file:///Users/me/Library/Application%20Support/Google/Chrome/Default/Extensions/mclkkofklkfljcocdinagocijmpgbhab/5.8.0.2_0/chext_driver.js:222:34)
edit:1 Refused to load the image 'https://itty.bitty.site/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

edit:1 Error in event handler for (unknown): SecurityError: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.
    at getCookieValue (chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/js/contentscript.js:88:33)
    at chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/js/contentscript.js:52:33
    at chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/js/contentscript.js:207:13
edit:1 Refused to load the stylesheet 'https://itty.bitty.site/edit.css' because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' 'self'".

It does work for me in other browsers, including Version 69.0.3485.0 (Official Build) canary (64-bit) running without extensions.

**Comment by mayel** [comment]
Looks like the two extensions appearing in the error log are:

1. Google Input Tools
2. The Great Suspender

**Comment by mayel** [comment]
Disabling those extensions makes those specific errors go away, but not the other ones, and editor still doesn't work.

**Comment by alcor** [comment]
This is a blank edit page?

**Comment by methodbox** [comment]
I have the same issue. This is the page I get:

<img width="1681" alt="screen shot 2018-07-08 at 10 09 48 am" src="https://user-images.githubusercontent.com/12660440/42421236-de5166b0-8297-11e8-97c6-5c82b13f07b3.png">

**Comment by alcor** [comment]
shouldn't default-src 'self' be covering this case?

**Comment by alcor** [comment]
(added script-src: 'self' to see) Error still occurring?

**Comment by mayel** [comment]
It's now working for me, thanks @alcor 😄

**Comment by alcor** [comment]
Great :) Closing for now

**Comment by methodbox** [comment]
Seems like by Google’s definition default-src ‘self’ should be sufficient but apparently not.

Thanks for the fix.  Will test later to confirm.

**Comment by methodbox** [comment]
Just wanted to confirm this is working for me as well.
