### ISSUE TITLE
[info] Any global JavaScript code in HTML must use semicolons

### ISSUE THREAD

**Issue by SteveALee** [alcor/itty-bitty#23]
Compression concatenates whitespace so EOLS are lost as expression terminators if you use the no semicolons style. You'll see token errors in the console as multiple expression appear on the same line.

**Comment by alcor** [comment]
Compression should not be stripping spaces. Can you provide an example?

**Comment by SteveALee** [comment]
Sure,

using Chrome on WIndows 10

```
  <html lang="en">
    <body>
    <script>
        const a= 3
        console.info(a)
      </script>
    </body>
  </html>
```

add the 2 semis and all is well.
gives

```
 SCRIPT1004: SCRIPT1004: Expected ';'
html;charset=utf-8;base64,wqAgPGh0bWwgbGFuZz0iZW4iPiDCoMKgwqAgPGJvZHk+IMKgIMKgIDxzY3JpcHQ+IMKgwqDCoMKgwqDCoMKgIGNvbnN0IGE9IDMgwqDCoMKgwqDCoMKgwqAgY29uc29sZS5pbmZvKGEpIMKgwqDCoMKgwqAgPC9zY3JpcHQ+IMKgwqDCoCA8L2JvZHk+IMKgIDwvaHRtbD4g (1,71)
```

**Comment by alcor** [comment]
Hmm.. this seems to be limited to html pasted raw into the editor. for any complex scripting, I'd suggest using codepen.io or dragging an HTML file into the view. 

This is a bug though, it gets converted to: `<script>         const a= 3         console.info(a)       </script>`

**Comment by alcor** [comment]
Fixed!

**Comment by SteveALee** [comment]
See commit https://github.com/alcor/itty-bitty/commit/228559a68a543086fc62d6b34601b4aa5f2b5e5c
