### ISSUE TITLE
Tab Advanced in your site

### ISSUE THREAD

**Issue by hn7xakns** [alcor/itty-bitty#26]
The page say this is command:
echo -n 'hello world' | lzma -9 | base64 | printf "https://itty.bitty.site/#%s\n" "$(cat -)"

but 
the right is:

echo -n 'hello world' | lzma -9 | base64 | printf "https://itty.bitty.site/#/%s\n" "$(cat -)"
with "/#/%s" --->>> /

pt-br
A página "Avançado" diz sobre o comando a ser executado porém falta uma barra "/" antes do "%"
por isso o comando não retorna um url válido

**Comment by Ken-g6** [comment]
It doesn't work very well with a long string either.  E.g.:
```
$ echo -n 'hello world, this is a test of a very long non-repetitive string' | lzma -9 | base64 | printf "https://itty.bitty.site/#/%s\n" "$(cat -)"
https://itty.bitty.site/#/XQAAAAL//////////wA0GUnujekXiTozX/32ROYTGBbyLoSiiZnCSV2EP+xuNafmZDtYSoYf7lWs
f6bev5Y6bFNV8Q7Te0Z+asmrH/736EA=
```
A "-w0" is needed to prevent wrapping.
```
$ echo -n 'hello world, this is a test of a very long non-repetitive string' | lzma -9 | base64 -w0 | printf "https://itty.bitty.site/#/%s\n" "$(cat -)"
https://itty.bitty.site/#/XQAAAAL//////////wA0GUnujekXiTozX/32ROYTGBbyLoSiiZnCSV2EP+xuNafmZDtYSoYf7lWsf6bev5Y6bFNV8Q7Te0Z+asmrH/736EA=
```

**Comment by alcor** [comment]
Updated http://advanced.bitty.site with these. The -w0 option is only required on linux.

Thank you :)
