### ISSUE TITLE
Refactor project

### ISSUE THREAD

**Issue by skoshx** [alcor/itty-bitty#30]
So I've been looking at this repository for a while now, and I cannot understand one bit of any of this.

Why is there minified files in the src directory?
Why is there minified javascript in the index.html file?

No dist folder for the minified shit? What the fuck is this? Somebody who fucking understands this code please fucking refactor this shit.

**Comment by alcor** [comment]
Working on it. I want there to be a single minified index file (to reduce network requests), but I haven't found a good packager/config that can do it. 

The four lines in the index file represent substitutions for 
<script src="lzma/lzma-d-min.js"></script>
<script src="data.js"></script>
<script src="index.js"></script>
<link rel="stylesheet" href="index.css">

Respectively. Hope that helps in the meantime.

**Comment by p3k** [comment]
please mind your manners  @SkoshRG

**Comment by SkoshRG** [comment]
@alcor I would recommend using something like HTML5Boilerplate or Googles Web Starter Kit for web projects, they speed up development and keep everything neat well structured. They are very easy to setup too.

@p3k Yes, my bad

**Comment by rayfoss** [comment]
@SkoshRG

I for one, like Paul Irish, am against dist folders for "minified shit"... there is a releases feature on gitlab/github. They increase git size dramatically, and make it a real pain to build in dev, as you can't ignore them easily.

This is a very wierd project with extreme requirements, I would not blame you for hand coding a build process.
