### ISSUE TITLE
Does itty-bitty works on Microsoft Edge?

### ISSUE THREAD

**Issue by callmehanu** [alcor/itty-bitty#31]
I don't be sure what technology do you use, but at least in Edge... Itty bitty doesn't work fine.
Sometimes the links just don't work.

**Comment by alcor** [comment]
Edge only supports urls up to 2KB. Anything longer should fail with an error message. Is it not showing?

**Comment by callmehanu** [comment]
![itty-bitty on edge](https://user-images.githubusercontent.com/13230502/42585492-650755c4-84fb-11e8-913b-7a2fa1144e52.png)

**Comment by alcor** [comment]
Please include the link :)

**Comment by callmehanu** [comment]
Sure! Here is
[my test on itty bitty ](https://itty.bitty.site/#Why_Do_We_Fidget%253F/?XQAAAAJ3BAAAAAAAAAAjG8pCAzXDUPUhiSSHuHMtVYsIuDELsAArHZTK2DwzsbrVIRWHWovm3DQWhET1BfHvqm4RAfhEEs2M6Bqubs0UzrUfJjse93HrEVeuU6EK0J6PCBO35i18wyCvOgf4KpJjOwDPP5e/PeyW9Jw0tG2HdaoQ1LKjDX9kx6xUR+/AUbs5XS6UrGuAFODqWrJUdj0GMxQwEFIOAsEDZVd1+3eXtgU/NxQBd7iAEqnICTnjVXGE28dZI1EvBbmWa1gxSL+FaY434etmu6c//Z6rD0qEWpkiaLM0S4Ehr3SQHNqNTVaBZmydwhdWNUZ5h/B+Qr+h72U1cWR9v1jr6cYmDwCYkr6IBbsdTV1jSForf4I1w2J6BMTtmuhyRhBup+oK+GE3LORIxHeGKb15JkIRq16bXeZBmA8Z9LqBI+aCOSApnsMMkjSYCQKtlySCuBY+dlJ26KDtCCDBGrx0x0RfS0Q+cwxJ7omrSZ1SS1OZw4RM9AJ+ceytVeA063eYjvGdzAQsbH+cVOsXlttU2uK915cmtBFvjp3fIMXVwb4nwXoxa2aA5enmfaDjN9niw9MYNjRCirRBtbm0HKFs2058FOFu+FeGO8GNd4TrQcK2mxkjql8aR7yfpv/UJwN2LRtUp/N4RE2VHJpNCGVc8xJ7Nxp3n896+S9IK2hdsBXsKJPF4Ze0gc3TmWuGLmTMflKccUtq+qgrsEvQyM1teZ3JVZmavvO+KtVX7aJ75vtBXFT93tpRmfOE0LtNeY3QkJBLZCn8yo8aLMV+eHdNEjhl8yYUpvzyGa08Aa0ClJ2i3W+3PQqoCBXGuBu0yFR1a8Dq6P975glhL6CJ964naZZYL2mC1cfj6N8FjM83Qlb+ZF3zGSo9UaIktYEPOtNiFJIAm2Phq9WIa2Z/d4ykh0qkx27Fnve3DbSc//gf7qI=)

**Comment by alcor** [comment]
It appears to be working for me:
![capture](https://user-images.githubusercontent.com/563095/42703721-3af9a4ac-8682-11e8-85e2-7dd17b1b4fc5.PNG)

**Comment by callmehanu** [comment]
Yep... Seems that was a problem of Edge by itself. I upgrade it and all itty-bitty works great

**Comment by alcor** [comment]
Good ! Closing for now
