### ISSUE TITLE
How to import from codepen?

### ISSUE THREAD

**Issue by felippenardi** [alcor/itty-bitty#37]
The instructions tells us to paste the link into the editor... but nothing happens, see:
https://itty.bitty.site/#/?XQAAAAIkAAAAAAAAAAA0HSzgdXPvDKC8rwyKjY2h7ysyAvBKEHxmwTstCpIRizoYIhxv6Db//rCYAA==

**Comment by alcor** [comment]
It sometimes takes a second for it to download and update the url (it'll put a blue border around it).

This is what comes out when I paste:


https://itty.bitty.site/#/data:text/html;charset=utf-8;bxze64,XQAAAAINDQAAAAAAAAAeHMqHyTY4PyKmqfkwr6ooCXSIMxPQ7okSjV8DQaR8xaMIrq7vSfBmX8Ut3JshaODT5XOhWYG8UUt72oThxSo4UIBikG6+9bG3TTwsuaNqps1eVXyc2CtzTRiIQI0LZ8HEj4DiZl/6GxUskaa4pTKd8vfHz5Pw480hexc75gs4xdmptaOscUOJYkyzXnEGhjdi2kaZYoOxXxUrflT3RI9r4dR8yLcq7Zgbr7hgCxcqAX5WkEWMZT0Yq0H8uf2h7zgvRj9KvZG1bOLKw1uuZbBwAjIvoawIuhhTTLO6kG844MLgn//yW0iv2SYYEUDuXFGVe3OgxIxbj21QRMkmpMabdT3r4Z8OFf0U0t0Ca7D/5Z5i9vwc0u+r3dz0kPqbaUEkqYhiJ/P6rmElHw+TusqhOww6x02DjniEKv200s7i9aWpJRGpKs8SNxg+OkyPTBhqt/JXz80xb0huM9KsYr0a3xmxxopB92IOz03ZAcNxLDZpp9zlSCj/H1h8opalDHHAtMb15xKKY+CyMk4mWkL8Okwe/iBwR63HjymOgnUs0tfxMQUF+f3c1RvDnHHtc9eLKvzkH89SUE6ibVGMIaTjsrHzI50GIIaC4QAJLXGVXcS04yKna+I/slux7UJgzSLy1/XJKZLPkdBnlXiUMpyFBNJD43rknDQu81Clnx1VyCNqZw5kCULOwp8rxqEYytBqIUy4UzApgyEDgEnxmOfVQ3bXmm7WS1ylc22Lvr4dCtREuYHRpRRlbfnDcHFmpl8NG9xpRd/6h9S9MvU3YaY2LrWH/jtLuVEjEx4jkJVEe0npiv+ZeObJJXwwtGl3m5o9sgYS+LkE2RnS6bMkVS4MufWN3/pzSe6ycKqOKQUYsMjGsd6Mcn68O7dRsKSmgPYJ2FeriY4LkUYH0eyumxNQW2KNM6O2sKJMR4jDot9Dudeg5GyL88Gfv5lPCp4S+kw7tKiKnZx19aN/6S8PSmwJrwvJMU6F2LKmg9k8eEQJaS5H9b8obRG0xX1dbHS+Q8dkJs475AHCTMmVPl9Xsh0eCnTCU8Nq7VDbCd8OTNRF+HQPtJfHRTaqftfiGkJnTJim1EkDh6KFVzbN6IyXlKUM4pbrmVcEV5b7YgxaE4dKlRF8Pw3uy1ZAj/xcznk=

**Comment by felippenardi** [comment]
Thanks! Now it works :)

**Comment by felippenardi** [comment]
@alco I can paste any codepen URLs and have it embedded BUT the ones I create.

For example, I can't seem to make this link work:
https://codepen.io/felippenardi-the-sasster/pen/GBpvLZ

**Comment by alcor** [comment]
Fixed :) hyphens weren't included in the regex for usernames

**Comment by dustinmichels** [comment]
Ah! The problem was my ad blocker. I turned that off and it worked.
