### ISSUE TITLE
Idea : Use LZ-String for better compresson

### ISSUE THREAD

**Issue by bauripalash** [alcor/itty-bitty#38]
I'm looking on the project since the first day, I also started a similar project in summer but due to my exams, I couldn't complete it.

I used LZ-String from http://pieroxy.net/blog/pages/lz-string/index.html then used base64 to make it url safe, after this project I tested and found that LZ-String is giving better compression than any other lib.

So, I think it would be a good idea to use [LZ-String](https://github.com/pieroxy/lz-string/)

**Comment by alcor** [comment]
Is it smaller for longer strings? This is lzw, and it says:

> For performace comparison, I use LZMA level 1 as a comparison point.
> For strings smaller than 750 characters, this program is 10x faster than LZMA level 1. It produces smaller output.
> For strings smaller than 100 000 characters, this program is 10x faster than LZMA level 1. It produces bigger output.


What I care about is strings in the 3k range

**Comment by alcor** [comment]
My initial tests (the standard pages on itty.bitty)

`Size of sample is: 8635 https://codepen.io/jnjitkoff/pen/NzxNjq
edit.js:186 Size of compressed sample is: lzs:6116 lzma:5168
edit.js:184 Size of sample is: 2708 https://codepen.io/jnjitkoff/pen/wXbvMm
edit.js:186 Size of compressed sample is: lzs:2368 lzma:1956
edit.js:184 Size of sample is: 7048 https://codepen.io/jnjitkoff/pen/XYrzGe
edit.js:186 Size of compressed sample is: lzs:4988 lzma:3944
edit.js:184 Size of sample is: 1139 https://codepen.io/jnjitkoff/pen/RJbxeW
edit.js:186 Size of compressed sample is: lzs:676 lzma:644`

If base64 encoding (for the url) were not required this would be excellent (with significant space saving). But with it, it is almost always larger :(

**Comment by bauripalash** [comment]
Got it.
**When I tested, i forgot about base64.**

In Future, I'll let you know if I found any useful libraries which can be used in this project.

Thank You.

**Comment by alcor** [comment]
Thank you for the recommendation :) I got very excited for a minute until I remembered, too. I'm still looking at Brotli as an alternative, but there aren't any good JS implementations.

**Comment by bauripalash** [comment]
@alcor did you find any JavaScript implementation of brotli?

I found a repo, but it's not maintained for a year, https://github.com/devongovett/brotli.js/

**Comment by bauripalash** [comment]
And I just found another implementation in haxe , https://github.com/dominikhlbg/BrotliHaxe

Which also has a JavaScript version , https://github.com/dominikhlbg/BrotliHaxe/blob/master/javascript/brotli.js

**Comment by alcor** [comment]
287 KB is a lot to handle :( I'm trying to keep things small. I'll give it a try though. If the space savings are good enough, it might be worth it.

**Comment by dimaguy** [comment]
What if you optimize the strings to be compressed according to the length?
like smaller to lzstring and the others to the default?
