### ISSUE TITLE
FYI: Google Docs add-on

### ISSUE THREAD

**Issue by bjornbacklund** [alcor/itty-bitty#39]
Hello, I love the itty bitty idea! So much that we've released a Google Docs add-on that converts a Google Doc to a itty bitty site - [https://apps.docs365.io/AboutIttyBittyAddOn.aspx](https://apps.docs365.io/AboutIttyBittyAddOn.aspx)
Sorry for the spam,
---bjorn

**Comment by alcor** [comment]
That's really cool! Did you encode the url in the add-on?

**Comment by bjornbacklund** [comment]
Thanks. Yes, the encoding happens in the add-on.
---bjorn

**Comment by twMat** [comment]
@bjornbacklund 

>https://apps.docs365.io/AboutIttyBittyAddOn.aspx

Sounds great... but site is dead :-(

**Comment by bjornbacklund** [comment]
Yes, site has been decommissioned. Sorry about that.
