### ISSUE TITLE
Couldn’t you technically run any app?

### ISSUE THREAD

**Issue by abhinayar** [alcor/itty-bitty#4]
Not an “issue” per se and I haven’t gotten a chance to play with this so excuse the naive question, but if you’re compressing the raw html and serving it, couldn’t I- for example, run a whole React app on here and only keep the root div (GitHub kept rendering a real div when I added html..) as the only html? (Could even let the browser add the body for you)

**Comment by abhinayar** [comment]
Hmm okay so looks like the iframe it gets loaded in prevents some cross site scripting stuff but for the most part if you CDN your files you might not be able to get React working but a solid jQuery app seems very possible with external scripts, etc.

Super interesting, thanks for making this! Already have a couple of totally unpractical and unneeded ideas but hey...

**Comment by alcor** [comment]
The iframe is somewhat locked down, but some basic stuff should be workable :) Closing for now.
