### ISSUE TITLE
Host it on own server or host

### ISSUE THREAD

**Issue by univa64** [alcor/itty-bitty#50]
Hi!  
How can i host itty-bitty on own server or host?  
it runs in html static host or need to a server for handle js or etc?  
plz tell me about this

**Comment by Jinxiapu** [comment]
Just js&html, netlify or github page is enough.

**Comment by univa64** [comment]
I deployed itty-bitty on netlify with this config `netlify.toml`:  
```
base = ""
publish = "."
command = ""
```
and setup the netlify dns for my omn domain and connect that for my project
