### ISSUE TITLE
Codpen  / Documentation Question

### ISSUE THREAD

**Issue by dustinmichels** [alcor/itty-bitty#53]
Hi!

I love this project, and the option to create a site from a Codepen site is very nice. It's not clear to me from the documentation, if you use a Codepen link:

Does the _full content_ from the Codepen page get placed in the URL, or is the generated page pointing to Codepen site, so that if it gets deleted the itty bitty site will no longer work?

Thanks!

**Comment by alcor** [comment]
The full content gets placed into the URL, so you can revise or delete the original codepen and it will still work.
