### ISSUE TITLE
Codepen doesnt work

### ISSUE THREAD

**Issue by lenicyl** [alcor/itty-bitty#64]
Entering url of the pen just prints the link while using embed shows weird embed.... in both of the cases the link/embed isnt parsing

**Comment by atommarvel** [comment]
Seems like codepen's api changed. I made this [itty.bitty.app](https://itty.bitty.app/#sitemaker/data:text/html;charset=utf-8;bxze64,XQAAAAI5BQAAAAAAAAAeHMhnVbtj2GhVFxitjLymhAPrpFV9wH9oksXFYEN7uts/HFYjrNl3ebbkzVOzBxVtrexVpjxaBuEuaCn5zKYlcgvjW6Z5lBeNTxNS7KYHdFKYUuuWFopc3opuOu6hfZwKPlnDwNVbpScz8hGla6QATVxC+4a51jwCGNaMrelOk8Q9ZRonK4pW9ApOF+LPUZpFn/v1v3b5l+iPRoulsVdWs5Q1AVVwPQpNJrulNRgnDsejUPogqMJCGrfXDogvQuHigwz4+ewSoKaabwcMi+xAFGZSJwLCGlnun2W9Sms6AZTJnlTlgk8duBAXIb+hVjCLR3iHNOLPpryL5LF/UFVgYloD/jOAP+/aZu+RCRR2LMGcCoBGNXT+FvTYGEVI8KamTggxMOkR1zNGG4wI+SAGbd5JTZh0JFytmkFgT2mILMj1t8VMvbOsKVCOhIG9+hfbbKQs0wGFvUlC0/L/isxf1pGsOSJ48a10IwmlfL/a7/Uc10KQzTcnFWEJA1Wfrp2DOx61MFwxGdrlvedBTuIrkzrb9J9j19Qe9DuEzSZwjEWeJ3lbtodzq0AaEezhoDxfUktas3SdwWpCdAczkzKfC1gu0/WoNhlO7lWws6lRVKuPNy/0I5zR0UErqKUeclRigYn3fQh4j7aNglCbkcYgAzR9Z5+BxHQpn/7V4Pw=) that does similar functionality to what it used to do. Hope that helps!

**Comment by lenicyl** [comment]
i checked itty.bitty.site again and apparantly only stuff made by "pro" codepen accounts can be used

**Comment by alcor** [comment]
Yeah, It looks like only codepen pro accounts expose the html/css/js - bummer. I'll note it in the readme and see if I can find an alternative.
