### ISSUE TITLE
Forked site won't render

### ISSUE THREAD

**Issue by datallurgy** [alcor/itty-bitty#68]
I'm cloning itty-bitty on my own repo with [github pages](https://datallurgy.github.io/edit). I haven't modified anything so it should work the same as the original itty.bitty.site, but when I go to open my link, I get a blank page with the following in the console.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'script')
    at window.onload (index.js:99:73)
```
Link is [here](https://datallurgy.github.io/#invitation.html/data:text/html;charset=utf-8;bxze64,XQAAAAIMDAAAAAAAAAAeCEUG0O+oKBdZ2an16qclPsVsLFpNtYa4Jja7MS9liwVFmKFi3qhzb5/DHzZB6m6uFQyeAKRRIv+m6avS0/FluH00iMp9icLVIknIqvutS3XG8b0HsSzFR/2h2nWFzi4/bgTfcjYMIigbhqWsJcvYl1q1JLCcVKdNtqTDlZ7uMCOguuTkedAQUn/9x3S7TUoxK8AmkA/JG290YHdfeHX3qz5ZjUWpKb7cN+0p80B4mmig+N4pwr9m4qvu2sUA81duVEum540napJeCTn7RJ0+MVdX0ZMJ0uURvoX1qgBIzsT3bLR8tZjdG1D0kP8+bO019+Oh9EhUFAqh+v25nV//SxxD7LfCvm7kRetk5VvMRbd/4GgE3ZFWAlPYhYMeG1gm5Ev4Fv6O7ckLAjlV/R1jE326kuHOkICQ5nOmx0JxFHjWWuOiprThZWVUmH0YUKCP/KSFVoGWcv5OXSrOWJZA990ndX5e0gOkJpK1Litpw8JmJj/NF3FD0decQBisOxjkmBoWO++wrPP0jsxQa5+E5y16THCqXVbNqiAXmzvazORtW/4nsD0FCM/PC5SY2NjNTNgNmH0jfQc1N1g/CUJ/0u8f8WjS9UGZJ83a5JZ7knt+inRLMYD91TH+M1iIf0memCe2nTgjnoMoVSdrGIHZiDx4ZWqTTZg/0rj68W4qCXuJTuLawa/7Ar9rmxZju/ksdRf8P5Us9Y4cx6XXtEYnQQJHoXvGaCETPVdtFuGE0qRTVMKS8EJMC1imC8ryYfTBOZnESTlV2SR0vONa9RVWPWrfIJGuEznrXpIAJIzdVQQcdvBgBc3258E0UW2fgjVK2ZLbDr0TRGLXyEQGP29EEg2toOK/sH6BZAIm2+t+MrsUTGFOJUnvgdNJjnCRav2pxuC3lpZI+Cf9Uj3gSvpRP0ZAc4+BWPXBg1ZxaDhKVCuhz7Q5cpZJTS7WWH0hYpnkEj2oj+yjYoiWtr7mdSut9s1yAYC9pKBjjdktQAJeHFAA+zSIwfGPpXXQZz7ETlj6GVJdOm+tK6yX1PnKE8si1O66M117sm6xvnqj7lUQp8rsfHXMWmHlekaXWct8hEqqY8aUPiyuZn7akuIbRq8OfX/KoIHqFhMmhTQbrWADyPSnf+IP5rTRxwVI6l1vxQw4wFr2RO+uQ3n4uDzj/kn7CVNCGM4Ldme+5dFvzLsWBN3Qdk/FfqNpGr7AD1mPVcESbmmD9DZPaQxAdsVN9+8KWllBMQF4yERzK6UqhIaDikcgbwyrk7h/44CTK6E/06nyXuDV38u6x0O+o+zB1hoErZQzQFQzw3CUYUhaa4rk9DG9/JM/80LWHfLlutGd/J1sZ/MARgeFhWjQHrQ9b/32EEyjZzY46M5/i0WKoNrb3E0Eo7s/+Hse5S00nG0IagT/ypc6rV++YON2oMfeHbSZ7IZDzTVdXQkoS2bTF58mPR3Wfyx/jeBPycl5C1T6pBKPbfaPLxH4al6qnPxDG8WMl5Gavhd5gqzvEYIKwq7Eb0BS5pqGRyf/yJ1ZKg==).

Interestingly enough, it does render on itty.bitty.site. See [here](https://itty.bitty.site/#invitation.html/data:text/html;charset=utf-8;bxze64,XQAAAAIMDAAAAAAAAAAeCEUG0O+oKBdZ2an16qclPsVsLFpNtYa4Jja7MS9liwVFmKFi3qhzb5/DHzZB6m6uFQyeAKRRIv+m6avS0/FluH00iMp9icLVIknIqvutS3XG8b0HsSzFR/2h2nWFzi4/bgTfcjYMIigbhqWsJcvYl1q1JLCcVKdNtqTDlZ7uMCOguuTkedAQUn/9x3S7TUoxK8AmkA/JG290YHdfeHX3qz5ZjUWpKb7cN+0p80B4mmig+N4pwr9m4qvu2sUA81duVEum540napJeCTn7RJ0+MVdX0ZMJ0uURvoX1qgBIzsT3bLR8tZjdG1D0kP8+bO019+Oh9EhUFAqh+v25nV//SxxD7LfCvm7kRetk5VvMRbd/4GgE3ZFWAlPYhYMeG1gm5Ev4Fv6O7ckLAjlV/R1jE326kuHOkICQ5nOmx0JxFHjWWuOiprThZWVUmH0YUKCP/KSFVoGWcv5OXSrOWJZA990ndX5e0gOkJpK1Litpw8JmJj/NF3FD0decQBisOxjkmBoWO++wrPP0jsxQa5+E5y16THCqXVbNqiAXmzvazORtW/4nsD0FCM/PC5SY2NjNTNgNmH0jfQc1N1g/CUJ/0u8f8WjS9UGZJ83a5JZ7knt+inRLMYD91TH+M1iIf0memCe2nTgjnoMoVSdrGIHZiDx4ZWqTTZg/0rj68W4qCXuJTuLawa/7Ar9rmxZju/ksdRf8P5Us9Y4cx6XXtEYnQQJHoXvGaCETPVdtFuGE0qRTVMKS8EJMC1imC8ryYfTBOZnESTlV2SR0vONa9RVWPWrfIJGuEznrXpIAJIzdVQQcdvBgBc3258E0UW2fgjVK2ZLbDr0TRGLXyEQGP29EEg2toOK/sH6BZAIm2+t+MrsUTGFOJUnvgdNJjnCRav2pxuC3lpZI+Cf9Uj3gSvpRP0ZAc4+BWPXBg1ZxaDhKVCuhz7Q5cpZJTS7WWH0hYpnkEj2oj+yjYoiWtr7mdSut9s1yAYC9pKBjjdktQAJeHFAA+zSIwfGPpXXQZz7ETlj6GVJdOm+tK6yX1PnKE8si1O66M117sm6xvnqj7lUQp8rsfHXMWmHlekaXWct8hEqqY8aUPiyuZn7akuIbRq8OfX/KoIHqFhMmhTQbrWADyPSnf+IP5rTRxwVI6l1vxQw4wFr2RO+uQ3n4uDzj/kn7CVNCGM4Ldme+5dFvzLsWBN3Qdk/FfqNpGr7AD1mPVcESbmmD9DZPaQxAdsVN9+8KWllBMQF4yERzK6UqhIaDikcgbwyrk7h/44CTK6E/06nyXuDV38u6x0O+o+zB1hoErZQzQFQzw3CUYUhaa4rk9DG9/JM/80LWHfLlutGd/J1sZ/MARgeFhWjQHrQ9b/32EEyjZzY46M5/i0WKoNrb3E0Eo7s/+Hse5S00nG0IagT/ypc6rV++YON2oMfeHbSZ7IZDzTVdXQkoS2bTF58mPR3Wfyx/jeBPycl5C1T6pBKPbfaPLxH4al6qnPxDG8WMl5Gavhd5gqzvEYIKwq7Eb0BS5pqGRyf/yJ1ZKg==).

**Comment by alcor** [comment]
Thank you! Folded in equivalent changes :‌)
