### ISSUE TITLE
Encryption example doesn't work. Redirects to itty bitty homepage

### ISSUE THREAD

**Issue by trholding** [alcor/itty-bitty#71]
The following encryption example doesn't work for me. Redirects to itty bitty homepage:

echo -n 'hello world' | gzip -9 | openssl enc -aes-256-cbc | base64 | xargs -0 printf "https://itty.bitty.app//data:text/plain;cipher=aes;gzip64,%s\n"

**Comment by alcor** [comment]
So.... this *should* work now. give it a try?

**Comment by alcor** [comment]
oh, note, it should be:

echo -n 'hello world' | gzip -9 | openssl enc -aes-256-cbc | base64 | xargs -0 printf "https://itty.bitty.app/#/data:text/plain;cipher=aes;gzip64,%s\n"

It needs the hashtag

**Comment by trholding** [comment]
Thank you I'll check and update here.

**Comment by stet** [comment]
"Decryption Error - Incorrect password?"

**Comment by trholding** [comment]
@alcor Thanks and sorry that I couldn't reply.

I can confirm @stet 's issue

Try on this link:

https://itty.bitty.app/#/data:text/plain;cipher=aes;gzip64,U2FsdGVkX18+AKzjU3PklFa+NkPEujzpAvlQQQmfnHFAgu1NoPsetgdOf33F8Jyd

Password: test

Leads to decryption error

```
echo -n 'hello world' | gzip -9 | openssl enc -aes-256-cbc | base64 | xargs -0 printf "https://itty.bitty.app/#/data:text/plain;cipher=aes;gzip64,%s\n"
enter AES-256-CBC encryption password:
Verifying - enter AES-256-CBC encryption password:
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
https://itty.bitty.app/#/data:text/plain;cipher=aes;gzip64,U2FsdGVkX18+AKzjU3PklFa+NkPEujzpAvlQQQmfnHFAgu1NoPsetgdOf33F8Jyd
```
